/* Generated by Yosys 0.53+70 (git sha1 3ef4c91c3, clang++ 18.1.8 -fPIC -O3) */

module ha(a, b, sum, carry);
  input a;
  wire a;
  input b;
  wire b;
  output carry;
  wire carry;
  output sum;
  wire sum;
  sg13g2_and2_1 _0_ (
    .A(b),
    .B(a),
    .X(carry)
  );
  sg13g2_xor2_1 _1_ (
    .A(b),
    .B(a),
    .X(sum)
  );
endmodule
